### ISSUE TITLE
Create Our Own Service for DB

### ISSUE THREAD

**Issue by Gungz** [hasura/supergraph-top-n-challenge#5]
Hi,
Just want to confirm that creating our own service which uses the DB data means we create REST API, right?
Or it's something different ?

**Comment by nullxone** [comment]
[On the architecture image](https://github.com/hasura/supergraph-top-n-challenge/blob/efd453fd0a4bb2334cc5e7bc02d2a0ea90301795/architecture.png) The final `Gateway` piece should send the `Query Response` in GraphQL, but all the other communication can be REST or anything else you prefer.

**Comment by Gungz** [comment]
Thanks @nullxone, to submit I just need to make pull request on [submissions.md](https://github.com/hasura/supergraph-top-n-challenge/blob/master/submissions.md) and add my name, submission date and link to the my supergraph repository, right ? 

Btw may I know the script which you will use to do the test bench ? And can I submit more than one solution ?

I am asking for the test bench just to see what actually will be tested for example if I have 2 queries with same result, will you test both and see which one is the fastest ? Or I need to actually ensure the executed query is only what is mentioned as test case ?
